name: Update copyright year(s) in license file

on: 
  schedule:
    - cron: "*/5 * * * *" # 03:00 AM on January 1
  workflow_dispatch:

jobs:
  update-license-year:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: FantasticFiasco/action-update-license-year@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Merge pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Replace '--merge' with '--rebase' to rebase the commits onto the base
          # branch, or with '--squash' to squash the commits into one commit and merge
          # it into the base branch.
          # For more information regarding the merge command, please see
          # https://cli.github.com/manual/gh_pr_merge.
          gh pr merge --squash --delete-branch
